config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :form_of_payments
  resources :financial_accounts
  resources :hotels
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
    belongs_to :user

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]

  # GET /guests or /guests.json
  def index
    @guests = current_user.guests
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = current_user.guests.build(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to guest_url(@guest), notice: "Guest was successfully created." }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to guest_url(@guest), notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:name, :birthday, :gender, :user_id, :observation)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest) do |f| %>
  <% if guest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>
      <ul>
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div>
      <%= f.label "Nome", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.text_field :name, class: "form-control mb-3" %>
    </div>

    <div>
      <%= f.label "Data de nascimento", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.date_field :birthday, class: "form-control mb-3" %>
    </div>

    <div>
      <%= f.label :gender, "Gênero", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.select :gender, [["Masculino", true], ["Feminino", false]], {}, class: "form-control mb-3" %>
    </div>

    <div class="form-group">
      <%= f.label :observation, "Observações", class: "fw-bold text-muted" %>
      <%= f.text_area :observation, class: "form-control" %>
    </div>



    <div class="d-flex gap-2 mt-3">
      <%= f.submit @guest.new_record? ? "Criar hóspede" : "Atualizar hóspede", class: "btn btn-sm btn-primary" %>
      <%= link_to "Voltar", guests_path, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/guests/_guest.html.erb
<div id="<%= dom_id guest %>" class="container">
<% if guest.user_id == current_user.id %>

  <p class="text-muted mt-2 fw-bold fs-1">
    <%= guest.name %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5">Data de nascimento:</strong>
    <%= guest.birthday %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5" >Genêro:</strong>
    <%= guest.gender ? "Masculino" : "Feminino" %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5" >Observação</strong>
    <textarea class="form-control mt-1" readonly><%= guest.observation %></textarea>
  </p>
<% end %>

</div>

app/views/guests/edit.html.erb
<% if @guest.user_id == current_user.id %>
    <h1  class="text-center text-muted mt-2">Editar hóspede</h1>
    <%= render "form", guest: @guest %>
<% end %>

app/views/guests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center text-muted mt-2">Hóspedes</h1>

<div id="guests" class="table-responsive container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Data de nascimento</th>
        <th scope="col">Gênero</th>
        <th scope="col">Criado</th>
        <th scope="col">Atualizado</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @guests.each do |guest| %>
        <tr>
          <td><%= guest.name %></td>
          <td><%= guest.birthday.strftime('%d/%m/%Y') %></td>
          <td><%= guest.gender ? "Masculino" : "Feminino" %></td>
          <td><%= guest.created_at.strftime('%d/%m/%Y') %></td>
          <td><%= guest.updated_at.strftime('%d/%m/%Y') %></td>
          <td class="d-flex gap-1">
            <%= link_to "Mostrar", guest, class: "btn btn-sm btn-primary" %>
            <%= link_to "Editar", edit_guest_path(guest), class: "btn btn-sm btn-secondary" %>
            <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Excluir</button>          
          </td>
        </tr>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja realmente excluir esse hospede ?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                Essa ação não poderá ser desfeita
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <%= button_to "Excluir", guest, method: :delete, class: "btn btn-sm btn-danger"%>
              </div>
            </div>
          </div>
        </div>

      <% end %>

    </tbody>
  </table>
<%= link_to "Novo Hóspede", new_guest_path, class: "btn btn-sm btn-primary float-end" %>
</div>

app/views/guests/new.html.erb
<h1 class="text-center text-muted mt-2">Novo Hóspede</h1>

<%= render "form", guest: @guest %>

<br>

app/views/guests/show.html.erb
<% if @guest.user_id == current_user.id %>
<p style="color: green"><%= notice %></p>
  <%= render @guest %>
  <div class="d-flex gap-2 container">
    <%= link_to "Voltar", guests_path, class: "btn btn-sm btn-secondary" %>
    <%= link_to "Editar", edit_guest_path(@guest), class: "btn btn-sm btn-primary"  %> 
    <%= button_to "Apagar", @guest, method: :delete, class: "btn btn-sm btn-danger" %>
  </div>
<% end %>