config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :form_of_payments
  resources :financial_accounts
  resources :hotels
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/form_of_payment.rb
class FormOfPayment < ApplicationRecord
    belongs_to :financial_account
end

app/controllers/form_of_payments_controller.rb
class FormOfPaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_form_of_payment, only: %i[ show edit update destroy ]

  # GET /form_of_payments or /form_of_payments.json
  def index
    @form_of_payments = FormOfPayment.all
  end

  # GET /form_of_payments/1 or /form_of_payments/1.json
  def show
  end

  # GET /form_of_payments/new
  def new
    @form_of_payment = FormOfPayment.new
    @financial_accounts = current_user.financial_accounts
  end

  # GET /form_of_payments/1/edit
  def edit
    @financial_accounts = current_user.financial_accounts
  end

  # POST /form_of_payments or /form_of_payments.json
  def create
    @form_of_payment = FormOfPayment.new(form_of_payment_params)

    respond_to do |format|
      if @form_of_payment.save
        format.html { redirect_to form_of_payment_url(@form_of_payment), notice: "Criado com sucesso." }
        format.json { render :show, status: :created, location: @form_of_payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form_of_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_of_payments/1 or /form_of_payments/1.json
  def update
    respond_to do |format|
      if @form_of_payment.update(form_of_payment_params)
        format.html { redirect_to form_of_payment_url(@form_of_payment), notice: "Atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @form_of_payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form_of_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_of_payments/1 or /form_of_payments/1.json
  def destroy
    @form_of_payment.destroy

    respond_to do |format|
      format.html { redirect_to form_of_payments_url, notice: "Apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_of_payment
      @form_of_payment = FormOfPayment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_of_payment_params
      params.require(:form_of_payment).permit(:name, :financial_account_id)
    end
end

app/helpers/form_of_payments_helper.rb
module FormOfPaymentsHelper
end

app/views/form_of_payments/_form.html.erb
<%= form_with(model: form_of_payment) do |f| %>
  <% if form_of_payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form_of_payment.errors.count, "error") %> prohibited this form_of_payment from being saved:</h2>

      <ul>
        <% form_of_payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">

    <div>
      <%= f.label "Nome da forma de pagamento", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.text_field :name, class: "form-control mb-3" %>
    </div>

    <div class="form-group">
      <%= f.label :financial_account_id, "Conta Bancaria", class: "fw-bold text-muted" %>
      <%= f.select :financial_account_id, options_from_collection_for_select(@financial_accounts, :id, :bank, f.object.financial_account_id), { include_blank: "Selecione uma conta financeira" }, required: true, class: "form-control mb-3" %>
    </div>

    <div class="d-flex gap-2 mt-3">
      <%= f.submit @form_of_payment.new_record? ? "Criar forma de pagamento" : "Atualizar forma de pagamento", class: "btn btn-sm btn-primary"  %>
      <%= link_to "Voltar", form_of_payments_path, class: "btn btn-sm btn-secondary"  %>
    </div>
  </div>
<% end %>

app/views/form_of_payments/_form_of_payment.html.erb
<div id="<%= dom_id form_of_payment %>"class="container">
<% if form_of_payment.financial_account.user_id == current_user.id %>
  <p>
    <strong class="text-muted mt-2 fw-bold fs-5" >Name:</strong>
    <%= form_of_payment.name %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5" >Conta pertencente:</strong>
    <%= form_of_payment.financial_account.bank  %>
  </p>
<% end %>
</div>

app/views/form_of_payments/edit.html.erb
<% if @form_of_payment.financial_account.user_id  == current_user.id %>
    <h1 class="text-center text-muted mt-2">Editar forma de pagamento</h1>
    <%= render "form", form_of_payment: @form_of_payment %>
<% end %>

app/views/form_of_payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center text-muted mt-2">Formas de pagamento</h1>

<div id="form_of_payments" class="table-responsive container">
  <table class="table">
  <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Nome da Conta</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
  <% @form_of_payments.each do |form_of_payment| %>
      <tr>
        <% if form_of_payment.financial_account.user_id == current_user.id %>
        <td><%= form_of_payment.name %></td>
        <td><%= form_of_payment.financial_account.bank %></td>
        <td>
            <%= link_to "Editar", edit_form_of_payment_path(form_of_payment), class: "btn btn-sm btn-secondary" %>
            <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Excluir</button> 
        </td>
      </tr>
 <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja realmente excluir essa forma de pagamento ?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                Essa ação não poderá ser desfeita
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <%= button_to "Excluir", form_of_payment, method: :delete, class: "btn btn-sm btn-danger"%>
              </div>
            </div>
          </div>
        </div>
    </tbody>
  <% end %>
  <% end %>
  </table>
<%= link_to "Nova forma de pagamento", new_form_of_payment_path, class: "btn btn-sm btn-primary float-end" %>
</div>

app/views/form_of_payments/new.html.erb
<h1 class="text-center text-muted mt-2">Nova forma de pagamento</h1>

<%= render "form", form_of_payment: @form_of_payment %>

<br>

app/views/form_of_payments/show.html.erb
<p style="color: green"><%= notice %></p>
<% if @form_of_payment.financial_account.user_id  == current_user.id %>
  <%= render @form_of_payment %>
  <div class="d-flex gap-2 container">
    <%= link_to "Voltar", form_of_payments_path, class: "btn btn-sm btn-secondary" %>
    <%= link_to "Editar", edit_form_of_payment_path(@form_of_payment), class: "btn btn-sm btn-primary" %> 
  </div>
<% end %>