config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :form_of_payments
  resources :financial_accounts
  resources :hotels
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    HOTEL_TYPES = ["Matriz", "Filial"].freeze
    belongs_to :user
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = current_user.hotels
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = current_user.hotels.build(hotel_params)


    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :cnpj, :phone, :responsible, :hotel_type, :user_id)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |f| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row gy-3">

      <div class="col-md-6">
        <%= f.label :name, style: "display: block", class: "fw-bold text-muted" %>
        <%= f.text_field :name, class: "form-control mb-3" %>
      </div>

      <div class="col-md-6">
        <%= f.label :cnpj, style: "display: block", class: "fw-bold text-muted" %>
        <%= f.text_field :cnpj, class: "form-control mb-3" %>
      </div>

    </div>

    <div>
      <%= f.label "Telefone", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.text_field :phone, class: "form-control mb-3" %>
    </div>

    <div>
      <%= f.label "Responsável", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.text_field :responsible, class: "form-control mb-3"%>
    </div>

    <div>
      <%= f.label "Tipo do hotel", style: "display: block", class: "fw-bold text-muted" %>
      <%= f.select :hotel_type, Hotel::HOTEL_TYPES, {}, class: "form-select" %>
    </div>

    <div class="d-flex gap-2 mt-3">
      <%= f.submit @hotel.new_record? ? "Criar hotel" : "Atualizar hotel", class: "btn btn-sm btn-primary" %>
      <%= link_to "Voltar", hotels_path, class: "btn btn-sm btn-secondary" %>
    </div>

  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>"class="container">
<% if hotel.user_id == current_user.id %>
  <p class="text-muted mt-2 fw-bold fs-1">
    <%= hotel.name %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5">Cnpj:</strong>
    <%= hotel.cnpj %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5">Phone:</strong>
    <%= hotel.phone %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5">Responsible:</strong>
    <%= hotel.responsible %>
  </p>

  <p>
    <strong class="text-muted mt-2 fw-bold fs-5">Tipo:</strong>
    <%= hotel.hotel_type %>
  </p>
<% end %>

</div>

app/views/hotels/edit.html.erb
<% if @hotel.user_id == current_user.id %>
    <h1 class="text-center text-muted mt-2">Editar Hotel</h1>
    <%= render "form", hotel: @hotel %>
<% end %>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center text-muted mt-2">Hotels</h1>

<div id="hotels" class="table-responsive container">
  <table class="table">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Responsável</th>
          <th scope="col">Tipo</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
      <% @hotels.each do |hotel| %>
        <tr>
          <td><%= hotel.name %></td>
          <td><%= hotel.responsible %></td>
          <td><%= hotel.hotel_type %></td>
          <td class="d-flex gap-1">
            <%= link_to "Mostrar", hotel, class: "btn btn-sm btn-primary" %>
            <%= link_to "Editar", edit_hotel_path(hotel), class: "btn btn-sm btn-secondary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to "Novo Hotel", new_hotel_path, class: "btn btn-sm btn-primary float-end" %>
</div>

app/views/hotels/new.html.erb
<h1 class="text-center text-muted mt-2">Novo Hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

app/views/hotels/show.html.erb
<% if @hotel.user_id == current_user.id %>
<p style="color: green"><%= notice %></p>
<%= render @hotel %>
  <div class="d-flex gap-2 container">
    <%= link_to "Voltar", hotels_path, class: "btn btn-sm btn-secondary" %>
    <%= button_to "Apagar", @hotel, method: :delete, class: "btn btn-sm btn-danger" %>
  </div>
<% end %>